trigger:
  branches:
    include:
      - main

variables:
  resourceGroup: 'Demo-RG'
  location: 'eastus'
  storageAccountName: 'demostorage$(Build.BuildId)'
  templateFile: 'infra/storage.bicep'

stages:
- stage: Deploy
  displayName: 'Deploy Storage Account'
  jobs:
  - job: DeployInfra
    displayName: 'Deploy Infra via Bicep'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: Bash@3
      displayName: 'Login to Azure using Managed Identity'
      inputs:
        targetType: 'inline'
        script: |
          echo "Logging into Azure using Managed Identity..."
          az login 
          # Optional: set subscription if multiple exist
          # az account set --subscription <subscription-id>

    - task: Bash@3
      displayName: 'Deploy Storage Account using Bicep'
      inputs:
        targetType: 'inline'
        script: |
          echo "Creating resource group if not exists..."
          az group create --name $(resourceGroup) --location $(location)

          echo "Deploying Storage Account using Bicep template..."
          az deployment group create \
            --resource-group $(resourceGroup) \
            --template-file $(templateFile) \
            --parameters storageAccountName=$(storageAccountName) \
            --only-show-errors \
            --output none
